version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: jnsh:master   # Required. Must be in the same fork network.
    mergeMethod: rebase     # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    assignees:
      - Briffou
    reviewers:              # Optional
      - Briffou
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - Briffou
  - base: arc-flatabulous
    upstream: master        # Required. Can be a branch in the same forked repo.
    mergeMethod: rebase
    assignees:              # Optional
      - Briffou
    reviewers:              # Optional
      - Briffou
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - Briffou
  - base: arc-qogir
    upstream: master        # Required. Can be a branch in the same forked repo.
    mergeMethod: rebase
    assignees:              # Optional
      - Briffou
    reviewers:              # Optional
      - Briffou
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - Briffou

